/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hawkjasruzxwjcmsjvvg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhhd2tqYXNydXp4d2pjbXNqdnZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMjE4MzQsImV4cCI6MjA3NTY5NzgzNH0.gZfLAucCk58fzspTu-MqEFqpZFQ-eueKdD5Bjwk-WCE"